<a href="https://colab.research.google.com/github/Susanta2006/Colab/blob/main/Vector1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
w=np.array([1,4,9])
x=np.array([2,7,4])
s=w+x
print("First vector: ",w)
print("Second vector: ",x)
print("Sum of two vectors: ",s)

First vector:  [1 4 9]
Second vector:  [2 7 4]
Sum of two vectors:  [ 3 11 13]


In [2]:
import numpy as np
n=np.array([[1,2,6,9],[2,8,5,9],[1,8,6,4]])
m=np.array([[8,2,9,1],[9,2,7,5],[8,9,2,9]])

Y=n+m
print("First Matrix: \n",n)
print("Second Matrix: \n",m)
print("Sum of Matrices: \n",Y)

First Matrix: 
 [[1 2 6 9]
 [2 8 5 9]
 [1 8 6 4]]
Second Matrix: 
 [[8 2 9 1]
 [9 2 7 5]
 [8 9 2 9]]
Sum of Matrices: 
 [[ 9  4 15 10]
 [11 10 12 14]
 [ 9 17  8 13]]


In [3]:
import numpy as np
# Define two 2D vectors
A = np.array([3, -2])
B = np.array([4, 5])

print("Vector A:", A)
print("Vector B:", B)

# 1. Vector Addition
C = A + B
print("A + B =", C)

# 2. Vector Subtraction
D = A - B
print("A - B =", D)

# 3. Scalar Multiplication
E = 2 * A
print("2 * A =", E)

# (Optional extra: Dot Product, just for completeness)
dot_product = np.dot(A, B)
print("A · B =", dot_product)


Vector A: [ 3 -2]
Vector B: [4 5]
A + B = [7 3]
A - B = [-1 -7]
2 * A = [ 6 -4]
A · B = 2
